function chooseRestaurant() {
    const restaurants = [
        // Favorites
        "Joy Luck",
        "Boba World",
        "Pizza Hut",
        "The Pie Pizzeria",
        "Dominos",
        "MOD Pizza", 
        "Mo' Bettahs", 
        "Ichiro Ramen House",
        "Rancheritos",
        "Taggart's Grill",
        "Sweeto Burrito",
        "Café Zupas",
        "Culver's",
        "Nielsen's Frozen Custard",
        "Costa Vida",
        "Cafe Rio",
        "Plates & Palates",
        "The Cheesecake Factory",
        "China Platter",
        "The Mandarin",
        "Blacksmith Ice Cream Co.",
        "Chik-fil-A",
        "Super Chix",
        "Del Taco",
        "Atlantis Burgers",
        "Crown Burger",
        "Apollo Burger",
        "Five Guys",
        "RJ Grill",
        "Hungry Hawaiian",
        "Janet's Sunshine Café",
        "Chipotle",
        "Costco Food Court",
        "Vito's",
        "Bountiful Greek Café",
        "Cubby's",
        "Panda Express",
        "Sushi Burrito",
        "Sawadee Thai Restaurant",
        "CHOM Burger",
        "Ramblin Roads",
        "Texas Roadhouse",
        "Global Place Somali Restaurant",
        "Zao Cafe",
        "Royal India Bountiful",
        "Garage on Beck",
        "Alice's Kitchen",
        "Burger Bar",
        "Rosa's Cafe",
        "Lean Thai",
        "Cupbop",
        "Costa del Sol",
        "Maddox",
        "Morty's Cafe",
        "Tandoori Oven",
        "In-N-Out",
        "Himalayan Flavor-Logan",
        "MayMoes Cajun Grill",
        "Royal Express Logan",
        "Shake Shack",
        "Cafe Sabor",
        "Z Brothers Pizza",
        "Santorini's Greek Grill",
        "Fuji Sushi",
        "W Thai Chef",
        "Kokonut Island Grill",
        "Nico's Restaurant",
        "Chubby's Mexican",
        "El Tacazo Taco Stand",
        "Cafe Shambala",
        "Old Bridge Cafe",
        "El Rocoto Peruvian",

        // New Restaurants recommended by ChatGPT
        "Log Haven",
        "Handle",
        "The Copper Onion",
        "Takashi",
        "Tupelo",
        "The Paris",
        "Current Fish & Oyster",
        "Red Iguana",
        "Hell's Backbone Grill",
        "The Farm",
        "Bambara",
        "The Front",
        "The Rest",
        "Alamexo",
        "Pago",
        "The Tin Angel",
        "The Eating Establishment",
        "The Vertical Diner",
        "The Red Moose Lodge",
        "The Wild Grape",
        "The Blue Lemon",
        "The Red Stone",
        "The Red Chair",
        "The Market Street Grill",
        "The Bistro at Red Butte Garden",
        "The Snow Garden",
        "The Swallow",
        "The Tree Room",
        "The Riverhorse on Main",
        "The Wasatch Brew Pub",
        "Pallet",
        "Valter's Osteria"
    ];

    const random = Math.floor(Math.random() * restaurants.length);
    document.getElementById('your-restaurant-picked').innerHTML = (restaurants[random]);

    let restaurantCount = restaurants.length;
    document.getElementById("count-string").innerHTML = `${restaurantCount} total restaurants...you're going to: `;
}
